---
description: 컴파일러 오류 CS0156
title: 컴파일러 오류 CS0156
ms.date: 07/20/2015
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
ms.openlocfilehash: 3abffbc5ee21ce588a8d5b6c7e980fcc7f7bc2f0
ms.sourcegitcommit: d579fb5e4b46745fd0f1f8874c94c6469ce58604
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 08/30/2020
ms.locfileid: "89132224"
---
# <a name="compiler-error-cs0156"></a><span data-ttu-id="ce4ef-103">컴파일러 오류 CS0156</span><span class="sxs-lookup"><span data-stu-id="ce4ef-103">Compiler Error CS0156</span></span>
<span data-ttu-id="ce4ef-104">바로 바깥쪽 catch 절에 중첩된 finally 절에는 인수가 없는 throw 문을 사용할 수 없습니다.</span><span class="sxs-lookup"><span data-stu-id="ce4ef-104">A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause</span></span>  
  
 <span data-ttu-id="ce4ef-105">매개 변수가 없는 [throw](../language-reference/keywords/throw.md) 문은 매개 변수를 사용하지 않는 **catch** 절에서만 나타날 수 있습니다.</span><span class="sxs-lookup"><span data-stu-id="ce4ef-105">A [throw](../language-reference/keywords/throw.md) statement with no parameters can only appear in a **catch** clause that takes no parameters.</span></span>  
  
 <span data-ttu-id="ce4ef-106">자세한 내용은 [예외 및 예외 처리](../programming-guide/exceptions/index.md)를 참조 하세요.</span><span class="sxs-lookup"><span data-stu-id="ce4ef-106">For more information, see [Exceptions and Exception Handling](../programming-guide/exceptions/index.md).</span></span>  
  
 <span data-ttu-id="ce4ef-107">다음 샘플에서는 CS0156을 생성합니다.</span><span class="sxs-lookup"><span data-stu-id="ce4ef-107">The following sample generates CS0156:</span></span>  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
