---
title: "'Throw' 피연산자는 'System.Exception'에서 파생되어야 합니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: 92fccbd2faac5580d28fef8cc02b51b23715f136
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84414948"
---
# <a name="throw-operand-must-derive-from-systemexception"></a>'Throw' 피연산자는 'System.Exception'에서 파생되어야 합니다.
`Throw` 에 제공된 인수는 `System.Exception` 인스턴스 또는 `System.Exception`에서 파생된 클래스의 인스턴스여야 합니다.  
  
 **오류 ID:** BC30665  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
- 다음 예제와 같이 `System.Exception`에서 파생된 인수를 사용합니다.  
  
    ```vb
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>참고 항목

- [Throw 문](../language-reference/statements/throw-statement.md)
- [Try...Catch...Finally 명령문](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [.NET의 예외 처리 및 Throw](../../standard/exceptions/index.md)
