---
title: "'Catch' 블록에 도달할 수 없습니다. '<exception>'이 같은 Try 문의 윗부분에서 처리되었습니다."
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 987a509b4b099a0a1f728f55dfb2b35a8770af3f
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395482"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>'Catch' 블록에 도달할 수 없습니다. '\<exception>'이 같은 Try 문의 윗부분에서 처리되었습니다.
코드의 `Catch` 블록이 앞의 `Try` 블록에서 처리되므로 도달할 수 없습니다.  
  
이 메시지는 기본적으로 경고입니다. 경고를 숨기거나 오류로 처리하는 방법에 대한 자세한 내용은 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)을 참조하세요.
  
 **오류 ID:** BC42031  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
- 중복 문을 제거합니다.  
  
## <a name="see-also"></a>참고 항목

- [Try/catch 블록을 사용 하 여 예외를 catch 하는 방법](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [사용자 필터 예외 처리기 사용](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally 명령문](../language-reference/statements/try-catch-finally-statement.md)
